spring.application.name=backend

#prefixo
server.servlet.context-path=/api

# Configuracao do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/advocacy
spring.datasource.username=postgres
spring.datasource.password=5desetembro
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracao do JPA e Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# configura��o do redis
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=

# Configuracoes de Erro do Servidor
server.error.include-message=always
server.error.include-binding-errors=always

# secrete
backend.security.secret=palavra-secreta
openai.api.key=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